<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_login1</name>
   <tag></tag>
   <elementGuidId>eff8804d-bbd5-4f01-b09f-bd510087ca16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__layout&quot;]/div/div/div/div/div/div/div/div[2]/div[2]/div/form/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__layout&quot;]/div/div/div/div/div/div/div/div[2]/div[2]/div/form/button</value>
   </webElementProperties>
</WebElementEntity>
